#sever
server:
  port: 8282
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

logging:
  level:
    kr.co.seoulit.insa: "info"

#DataSoruce
spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/xe
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: nexa77insa
    password: nexa77insa
  #spring.servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true

  cache:
    redis:
      time-to-live: 600s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true